### ISSUE TITLE
Filling with data fails by 5 serious bugs 

### ISSUE THREAD

**Issue by rcemper** [banksiaglobal/SleepTracker#16]
#1)  docker **terminal: 1.**  unclear! I assumed  backend is correct, in frontend /opt is just empty
#2)  /opt/venv/bin/activate fails:
. bash: /opt/venv/bin/activate: **Permission denied**
. corrected:   source bash: /opt/venv/bin/activate
#3)   **cd src**
. bash: cd: src: No such file or directory 
. correct: cd /code/src
#4)  **python .\sleepTrack\db_init.py**
. python: can't open file '/code/src/.sleepTrackdb_init.py': [Errno 2] No such file or directory
. no surprise \ is good for Windows not for bash in docker / is the way to go
. corrected:  python ./sleepTrack/db_init.py
#5)   File "/code/src/./sleepTrack/db_init.py", l
    import iris
. **ModuleNotFoundError: No module named 'iris'**

It is pretty obvious that you **NEVER** tried to execute and verify your own guidelines. 
. that's not the quality I expected from bankisaglobal

**Comment by bg-mgl** [comment]
I am sorry, Robert, that you were left alone with the mistakes and that we did not meet your expectations. 
The project was in the process of being finalised and we have fixed it, also thanks to your questions. Thank you for your attention to our project!

**Comment by rcemper** [comment]
Just a hint after my 400+ reviews I did.
Don't assume that the average user understands anything of your package.
If the guide for testing is almost a tutorial than
also the average user could folIow.
Also, small screenshots can help a lot.
