### ISSUE TITLE
all backend actions fail

### ISSUE THREAD

**Issue by rcemper** [banksiaglobal/SleepTracker#20]
http://localhost:9000/utils/create
http://localhost:9000/utils/generate

reply is always 
{"detail":"Method Not Allowed"}

WHAT CAN I do against this ?

And what Format do you expect  Do expect this as HTTP POST ????
> The body of each request must contain the following fields:
> url - url database
> password - password of database

Your guide is **the most horrible** I met over review > 400 packages in OEX

**Comment by rcemper** [comment]
spending hours of experimenting it turned out
You expect a POST request with a JSON body 
{
    "url": "k8s-45090081-a......_.us-east-1.amazonaws.com",
    "password": "anypw"
}

And why do have to find this myself ??
why is this not in the test description

**Comment by bg-mgl** [comment]
Dear Robert, we really appreciate your attention to our project and thank you for noticing the shortcomings. However, we are incredibly saddened by the fact that you have spent so much time trying to understand how the database is populated with test data. We have published a video for our project, which you can find at https://youtu.be/eZ9Wak831x4. It is less than 5 minutes long and we show how to work with the Swagger tool, where you can see all the information about the queries.
